# Khulnasoft App Copyright (C) 2017, Khulnasoft Inc. (License GPLv2)
version: '3.7'

services:
  khulnasoft.manager:
    build:
      context: khulnasoft-manager/
      args:
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
        KHULNASOFT_TAG_REVISION: ${KHULNASOFT_TAG_REVISION}
    image: khulnasoft/khulnasoft-manager:${KHULNASOFT_IMAGE_VERSION}
    hostname: khulnasoft.manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://khulnasoft.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - khulnasoft_api_configuration:/var/ossec/api/configuration
      - khulnasoft_etc:/var/ossec/etc
      - khulnasoft_logs:/var/ossec/logs
      - khulnasoft_queue:/var/ossec/queue
      - khulnasoft_var_multigroups:/var/ossec/var/multigroups
      - khulnasoft_integrations:/var/ossec/integrations
      - khulnasoft_active_response:/var/ossec/active-response/bin
      - khulnasoft_agentless:/var/ossec/agentless
      - khulnasoft_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

  khulnasoft.indexer:
    build:
      context: khulnasoft-indexer/
      args:
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
        KHULNASOFT_TAG_REVISION: ${KHULNASOFT_TAG_REVISION}
    image: khulnasoft/khulnasoft-indexer:${KHULNASOFT_IMAGE_VERSION}
    hostname: khulnasoft.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  khulnasoft.dashboard:
    build:
      context: khulnasoft-dashboard/
      args:
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
        KHULNASOFT_TAG_REVISION: ${KHULNASOFT_TAG_REVISION}
    image: khulnasoft/khulnasoft-dashboard:${KHULNASOFT_IMAGE_VERSION}
    hostname: khulnasoft.dashboard
    restart: always
    ports:
      - 443:443
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=admin
      - SERVER_SSL_ENABLED=false
      - KHULNASOFT_API_URL=https://khulnasoft.manager
    depends_on:
      - khulnasoft.indexer
    links:
      - khulnasoft.indexer:khulnasoft.indexer
      - khulnasoft.manager:khulnasoft.manager

volumes:
  khulnasoft_api_configuration:
  khulnasoft_etc:
  khulnasoft_logs:
  khulnasoft_queue:
  khulnasoft_var_multigroups:
  khulnasoft_integrations:
  khulnasoft_active_response:
  khulnasoft_agentless:
  khulnasoft_wodles:
  filebeat_etc:
  filebeat_var:
