version: '3.7'

services:
  khulnasoft.manager:
    image: khulnasoft/khulnasoft-manager:4.8.0
    hostname: khulnasoft.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://khulnasoft.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=khulnasoft-kui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - khulnasoft_api_configuration:/var/ossec/api/configuration
      - khulnasoft_etc:/var/ossec/etc
      - khulnasoft_logs:/var/ossec/logs
      - khulnasoft_queue:/var/ossec/queue
      - khulnasoft_var_multigroups:/var/ossec/var/multigroups
      - khulnasoft_integrations:/var/ossec/integrations
      - khulnasoft_active_response:/var/ossec/active-response/bin
      - khulnasoft_agentless:/var/ossec/agentless
      - khulnasoft_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/khulnasoft_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.manager.pem:/etc/ssl/filebeat.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/khulnasoft_cluster/khulnasoft_manager.conf:/khulnasoft-config-mount/etc/ossec.conf

  khulnasoft.indexer:
    image: khulnasoft/khulnasoft-indexer:4.8.0
    hostname: khulnasoft.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - khulnasoft-indexer-data:/var/lib/khulnasoft-indexer
      - ./config/khulnasoft_indexer_ssl_certs/root-ca.pem:/usr/share/khulnasoft-indexer/certs/root-ca.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.indexer-key.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft.indexer.key
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.indexer.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft.indexer.pem
      - ./config/khulnasoft_indexer_ssl_certs/admin.pem:/usr/share/khulnasoft-indexer/certs/admin.pem
      - ./config/khulnasoft_indexer_ssl_certs/admin-key.pem:/usr/share/khulnasoft-indexer/certs/admin-key.pem
      - ./config/khulnasoft_indexer/khulnasoft.indexer.yml:/usr/share/khulnasoft-indexer/opensearch.yml
      - ./config/khulnasoft_indexer/internal_users.yml:/usr/share/khulnasoft-indexer/opensearch-security/internal_users.yml

  khulnasoft.dashboard:
    image: khulnasoft/khulnasoft-dashboard:4.8.0
    hostname: khulnasoft.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://khulnasoft.manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=khulnasoft-kui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.dashboard.pem:/usr/share/khulnasoft-dashboard/certs/khulnasoft-dashboard.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.dashboard-key.pem:/usr/share/khulnasoft-dashboard/certs/khulnasoft-dashboard-key.pem
      - ./config/khulnasoft_indexer_ssl_certs/root-ca.pem:/usr/share/khulnasoft-dashboard/certs/root-ca.pem
      - ./config/khulnasoft_dashboard/opensearch_dashboards.yml:/usr/share/khulnasoft-dashboard/config/opensearch_dashboards.yml
      - ./config/khulnasoft_dashboard/khulnasoft.yml:/usr/share/khulnasoft-dashboard/data/khulnasoft/config/khulnasoft.yml
    depends_on:
      - khulnasoft.indexer
    links:
      - khulnasoft.indexer:khulnasoft.indexer
      - khulnasoft.manager:khulnasoft.manager

volumes:
  khulnasoft_api_configuration:
  khulnasoft_etc:
  khulnasoft_logs:
  khulnasoft_queue:
  khulnasoft_var_multigroups:
  khulnasoft_integrations:
  khulnasoft_active_response:
  khulnasoft_agentless:
  khulnasoft_wodles:
  filebeat_etc:
  filebeat_var:
  khulnasoft-indexer-data:
