network.host: khulnasoft2.indexer
node.name: khulnasoft2.indexer
cluster.initial_master_nodes:
        - khulnasoft1.indexer
        - khulnasoft2.indexer
        - khulnasoft3.indexer
cluster.name: "khulnasoft-cluster"
discovery.seed_hosts:
        - khulnasoft1.indexer
        - khulnasoft2.indexer
        - khulnasoft3.indexer
node.max_local_storage_nodes: "3"
path.data: /var/lib/khulnasoft-indexer
path.logs: /var/log/khulnasoft-indexer
plugins.security.ssl.http.pemcert_filepath: ${OPENSEARCH_PATH_CONF}/certs/khulnasoft2.indexer.pem
plugins.security.ssl.http.pemkey_filepath: ${OPENSEARCH_PATH_CONF}/certs/khulnasoft2.indexer.key
plugins.security.ssl.http.pemtrustedcas_filepath: ${OPENSEARCH_PATH_CONF}/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: ${OPENSEARCH_PATH_CONF}/certs/khulnasoft2.indexer.pem
plugins.security.ssl.transport.pemkey_filepath: ${OPENSEARCH_PATH_CONF}/certs/khulnasoft2.indexer.key
plugins.security.ssl.transport.pemtrustedcas_filepath: ${OPENSEARCH_PATH_CONF}/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.authcz.admin_dn:
- "CN=admin,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=khulnasoft1.indexer,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
- "CN=khulnasoft2.indexer,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
- "CN=khulnasoft3.indexer,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
- "CN=filebeat,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"
plugins.security.allow_default_init_securityindex: true
cluster.routing.allocation.disk.threshold_enabled: false
compatibility.override_main_response_version: true