version: '3.7'

services:
  khulnasoft.master:
    image: khulnasoft/khulnasoft-manager:4.8.0
    hostname: khulnasoft.master
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://khulnasoft1.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=khulnasoft-kui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - master-khulnasoft-api-configuration:/var/ossec/api/configuration
      - master-khulnasoft-etc:/var/ossec/etc
      - master-khulnasoft-logs:/var/ossec/logs
      - master-khulnasoft-queue:/var/ossec/queue
      - master-khulnasoft-var-multigroups:/var/ossec/var/multigroups
      - master-khulnasoft-integrations:/var/ossec/integrations
      - master-khulnasoft-active-response:/var/ossec/active-response/bin
      - master-khulnasoft-agentless:/var/ossec/agentless
      - master-khulnasoft-wodles:/var/ossec/wodles
      - master-filebeat-etc:/etc/filebeat
      - master-filebeat-var:/var/lib/filebeat
      - ./config/khulnasoft_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.master.pem:/etc/ssl/filebeat.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.master-key.pem:/etc/ssl/filebeat.key
      - ./config/khulnasoft_cluster/khulnasoft_manager.conf:/khulnasoft-config-mount/etc/ossec.conf

  khulnasoft.worker:
    image: khulnasoft/khulnasoft-manager:4.8.0
    hostname: khulnasoft.worker
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    environment:
      - INDEXER_URL=https://khulnasoft1.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    volumes:
      - worker-khulnasoft-api-configuration:/var/ossec/api/configuration
      - worker-khulnasoft-etc:/var/ossec/etc
      - worker-khulnasoft-logs:/var/ossec/logs
      - worker-khulnasoft-queue:/var/ossec/queue
      - worker-khulnasoft-var-multigroups:/var/ossec/var/multigroups
      - worker-khulnasoft-integrations:/var/ossec/integrations
      - worker-khulnasoft-active-response:/var/ossec/active-response/bin
      - worker-khulnasoft-agentless:/var/ossec/agentless
      - worker-khulnasoft-wodles:/var/ossec/wodles
      - worker-filebeat-etc:/etc/filebeat
      - worker-filebeat-var:/var/lib/filebeat
      - ./config/khulnasoft_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.worker.pem:/etc/ssl/filebeat.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.worker-key.pem:/etc/ssl/filebeat.key
      - ./config/khulnasoft_cluster/khulnasoft_worker.conf:/khulnasoft-config-mount/etc/ossec.conf

  khulnasoft1.indexer:
    image: khulnasoft/khulnasoft-indexer:4.8.0
    hostname: khulnasoft1.indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - khulnasoft-indexer-data-1:/var/lib/khulnasoft-indexer
      - ./config/khulnasoft_indexer_ssl_certs/root-ca.pem:/usr/share/khulnasoft-indexer/certs/root-ca.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft1.indexer-key.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft1.indexer.key
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft1.indexer.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft1.indexer.pem
      - ./config/khulnasoft_indexer_ssl_certs/admin.pem:/usr/share/khulnasoft-indexer/certs/admin.pem
      - ./config/khulnasoft_indexer_ssl_certs/admin-key.pem:/usr/share/khulnasoft-indexer/certs/admin-key.pem
      - ./config/khulnasoft_indexer/khulnasoft1.indexer.yml:/usr/share/khulnasoft-indexer/opensearch.yml
      - ./config/khulnasoft_indexer/internal_users.yml:/usr/share/khulnasoft-indexer/opensearch-security/internal_users.yml

  khulnasoft2.indexer:
    image: khulnasoft/khulnasoft-indexer:4.8.0
    hostname: khulnasoft2.indexer
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - khulnasoft-indexer-data-2:/var/lib/khulnasoft-indexer
      - ./config/khulnasoft_indexer_ssl_certs/root-ca.pem:/usr/share/khulnasoft-indexer/certs/root-ca.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft2.indexer-key.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft2.indexer.key
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft2.indexer.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft2.indexer.pem
      - ./config/khulnasoft_indexer/khulnasoft2.indexer.yml:/usr/share/khulnasoft-indexer/opensearch.yml
      - ./config/khulnasoft_indexer/internal_users.yml:/usr/share/khulnasoft-indexer/opensearch-security/internal_users.yml

  khulnasoft3.indexer:
    image: khulnasoft/khulnasoft-indexer:4.8.0
    hostname: khulnasoft3.indexer
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - khulnasoft-indexer-data-3:/var/lib/khulnasoft-indexer
      - ./config/khulnasoft_indexer_ssl_certs/root-ca.pem:/usr/share/khulnasoft-indexer/certs/root-ca.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft3.indexer-key.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft3.indexer.key
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft3.indexer.pem:/usr/share/khulnasoft-indexer/certs/khulnasoft3.indexer.pem
      - ./config/khulnasoft_indexer/khulnasoft3.indexer.yml:/usr/share/khulnasoft-indexer/opensearch.yml
      - ./config/khulnasoft_indexer/internal_users.yml:/usr/share/khulnasoft-indexer/opensearch-security/internal_users.yml

  khulnasoft.dashboard:
    image: khulnasoft/khulnasoft-dashboard:4.8.0
    hostname: khulnasoft.dashboard
    restart: always
    ports:
      - 443:5601
    environment:
      - OPENSEARCH_HOSTS="https://khulnasoft1.indexer:9200"
      - KHULNASOFT_API_URL="https://khulnasoft.master"
      - API_USERNAME=khulnasoft-kui
      - API_PASSWORD=MyS3cr37P450r.*-
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
    volumes:
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.dashboard.pem:/usr/share/khulnasoft-dashboard/certs/khulnasoft-dashboard.pem
      - ./config/khulnasoft_indexer_ssl_certs/khulnasoft.dashboard-key.pem:/usr/share/khulnasoft-dashboard/certs/khulnasoft-dashboard-key.pem
      - ./config/khulnasoft_indexer_ssl_certs/root-ca.pem:/usr/share/khulnasoft-dashboard/certs/root-ca.pem
      - ./config/khulnasoft_dashboard/opensearch_dashboards.yml:/usr/share/khulnasoft-dashboard/config/opensearch_dashboards.yml
      - ./config/khulnasoft_dashboard/khulnasoft.yml:/usr/share/khulnasoft-dashboard/data/khulnasoft/config/khulnasoft.yml
    depends_on:
      - khulnasoft1.indexer
    links:
      - khulnasoft1.indexer:khulnasoft1.indexer
      - khulnasoft.master:khulnasoft.master

  nginx:
    image: nginx:stable
    hostname: nginx
    restart: always
    ports:
      - "1514:1514"
    depends_on:
      - khulnasoft.master
      - khulnasoft.worker
      - khulnasoft.dashboard
    links:
      - khulnasoft.master:khulnasoft.master
      - khulnasoft.worker:khulnasoft.worker
      - khulnasoft.dashboard:khulnasoft.dashboard
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  master-khulnasoft-api-configuration:
  master-khulnasoft-etc:
  master-khulnasoft-logs:
  master-khulnasoft-queue:
  master-khulnasoft-var-multigroups:
  master-khulnasoft-integrations:
  master-khulnasoft-active-response:
  master-khulnasoft-agentless:
  master-khulnasoft-wodles:
  master-filebeat-etc:
  master-filebeat-var:
  worker-khulnasoft-api-configuration:
  worker-khulnasoft-etc:
  worker-khulnasoft-logs:
  worker-khulnasoft-queue:
  worker-khulnasoft-var-multigroups:
  worker-khulnasoft-integrations:
  worker-khulnasoft-active-response:
  worker-khulnasoft-agentless:
  worker-khulnasoft-wodles:
  worker-filebeat-etc:
  worker-filebeat-var:
  khulnasoft-indexer-data-1:
  khulnasoft-indexer-data-2:
  khulnasoft-indexer-data-3: