# IMPORTANT: Read and understand this template fully before applying it.

name: Scan dependencies for vulnerabilities with pip-audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 12 * * *"

jobs:
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          # IMPORTANT: You may need a more specific version here.
          python-version: "3.x"

      # IMPORTANT: You may or may not need this step, depending on
      # how your Python dependencies are specified.
      # You may also need to tweak it, depending on how your
      # Python package's build is configured.
      # See https://github.com/pypa/gh-action-pip-audit for details.
      - name: Install project
        run: |
          python -m venv /tmp/pip-audit-env
          source /tmp/pip-audit-env/bin/activate

          python -m pip install --upgrade pip
          python -m pip install .


      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.0.1
        with:
          # IMPORTANT: You may need additional or different settings here.
          # See https://github.com/pypa/gh-action-pip-audit for details.
          virtual-environment: /tmp/pip-audit-env
